
require('dotenv').config({ path: '.env.local' });
const admin = require('firebase-admin');
if (!admin.apps.length) {
  admin.initializeApp({ credential: admin.credential.cert({
    projectId: process.env.FIREBASE_ADMIN_PROJECT_ID,
    clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
    privateKey: process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g, '\n'),
  })});
}
const db = admin.firestore();
const courses = [
  {code:'PHI101',name:'Introduction to Philosophy',department:'Philosophy',year:1,semester:1},
  {code:'PHI106',name:'Plato: Symposium',department:'Philosophy',year:1,semester:1},
  {code:'PHI107',name:'Aristotelian Logic',department:'Philosophy',year:1,semester:1},
  {code:'BLH101',name:'Latin',department:'Philosophy',year:1,semester:1},
  {code:'BCG101',name:'Introduction to NT Greek',department:'Philosophy',year:1,semester:1},
  {code:'BCS101',name:'Introduction to Scripture',department:'Philosophy',year:1,semester:1},
  {code:'BAF101',name:'African Art & Culture',department:'Philosophy',year:1,semester:1},
  {code:'BSTH107',name:'Spiritual Theology',department:'Philosophy',year:1,semester:1},
  {code:'GES101',name:'Use of English 1',department:'Philosophy',year:1,semester:1},
  {code:'GES105A',name:'Agricultural/Renewable Natural Resources',department:'Philosophy',year:1,semester:1},
  {code:'GES106',name:'French',department:'Philosophy',year:1,semester:1},
  {code:'BMI201',name:'Italian I',department:'Philosophy',year:1,semester:1},
  {code:'BSTH107B',name:'Spiritual Theology (Yr 1 Sem 2)',department:'Philosophy',year:1,semester:2},
  {code:'PHI105',name:'Ancient Philosophy',department:'Philosophy',year:1,semester:2},
  {code:'BGES104',name:'Speech Techniques',department:'Philosophy',year:1,semester:2},
  {code:'BMI202',name:'Italian II',department:'Philosophy',year:1,semester:2},
  {code:'BCG102',name:'Introduction to NT Greek II',department:'Philosophy',year:1,semester:2},
  {code:'BLH102',name:'Latin II',department:'Philosophy',year:1,semester:2},
  {code:'PHI102',name:'Argument and Critical Thinking',department:'Philosophy',year:1,semester:2},
  {code:'GES107',name:'Reproductive Health',department:'Philosophy',year:1,semester:2},
  {code:'GES104',name:'Science and Mankind',department:'Philosophy',year:1,semester:2},
  {code:'PHI103',name:'Philosophy of Value',department:'Philosophy',year:1,semester:2},
  {code:'BGES105',name:'Research Methodology',department:'Philosophy',year:1,semester:2},
  {code:'PHI202',name:'Introduction to Logic',department:'Philosophy',year:2,semester:1},
  {code:'PHI203',name:'Ethics',department:'Philosophy',year:2,semester:1},
  {code:'PHI204',name:'Medieval Philosophy',department:'Philosophy',year:2,semester:1},
  {code:'PHI208',name:'Philosophy of Nature (Cosmology)',department:'Philosophy',year:2,semester:1},
  {code:'PHI206',name:'Introduction to Metaphysics',department:'Philosophy',year:2,semester:1},
  {code:'BPHI210',name:'Christianity and Philosophy',department:'Philosophy',year:2,semester:1},
  {code:'BSOC201',name:'Sociology',department:'Philosophy',year:2,semester:1},
  {code:'ECO201',name:'Introduction to Accounting',department:'Philosophy',year:2,semester:1},
  {code:'BSTH211',name:'Spiritual Theology (Yr 2)',department:'Philosophy',year:2,semester:1},
  {code:'PHI103B',name:'Philosophy of Value (Yr 2)',department:'Philosophy',year:2,semester:1},
  {code:'PHI110',name:'Aristotle: Nicomachean Ethics',department:'Philosophy',year:2,semester:1},
  {code:'GES105B',name:'Agricultural Science',department:'Philosophy',year:2,semester:1},
  {code:'PHI205',name:'Introduction to Political Philosophy',department:'Philosophy',year:2,semester:2},
  {code:'PHI207',name:'Introduction to African Philosophy',department:'Philosophy',year:2,semester:2},
  {code:'BPHI203',name:'Philosophy of God',department:'Philosophy',year:2,semester:2},
  {code:'BLI201',name:'Igbo Grammar',department:'Philosophy',year:2,semester:2},
  {code:'BUS201',name:'Introduction to Business Administration',department:'Philosophy',year:2,semester:2},
  {code:'BLA201',name:'Law of Contract',department:'Philosophy',year:2,semester:2},
  {code:'BPSY202',name:'Development of Psychology',department:'Philosophy',year:2,semester:2},
  {code:'BSTH211B',name:'Spiritual Theology (Yr 2 Sem 2)',department:'Philosophy',year:2,semester:2},
  {code:'PHI201',name:'Introduction to Epistemology',department:'Philosophy',year:2,semester:2},
  {code:'BPSY201',name:'Introduction to Psychology',department:'Philosophy',year:2,semester:2},
  {code:'BPHI209',name:'Introduction to Phil. Anthropology',department:'Philosophy',year:2,semester:2},
  {code:'BPHI206',name:'Ethical Values',department:'Philosophy',year:2,semester:2},
  {code:'GES201',name:'English Language',department:'Philosophy',year:2,semester:2},
  {code:'PHI301',name:'Metaphysics',department:'Philosophy',year:3,semester:1},
  {code:'PHI304',name:'Philosophy of Science',department:'Philosophy',year:3,semester:1},
  {code:'PHI305',name:'Social & Political Philosophy',department:'Philosophy',year:3,semester:1},
  {code:'PHI306',name:'Early Modern Philosophy',department:'Philosophy',year:3,semester:1},
  {code:'PHI307',name:'African Philosophy',department:'Philosophy',year:3,semester:1},
  {code:'PHI309',name:'Philosophy of Literature',department:'Philosophy',year:3,semester:1},
  {code:'PHI310',name:'Methodology of Research & Writing',department:'Philosophy',year:3,semester:1},
  {code:'PHI319',name:'Descartes: Discourse on Method',department:'Philosophy',year:3,semester:1},
  {code:'BSTH315',name:'Apostolic Vocation',department:'Philosophy',year:3,semester:1},
  {code:'BSOC301',name:'Sociology of Religion',department:'Philosophy',year:3,semester:1},
  {code:'BPSY302',name:'Psychology of Religion',department:'Philosophy',year:3,semester:1},
  {code:'GES301',name:'Introduction to Entrepreneurial Skills',department:'Philosophy',year:3,semester:1},
  {code:'PHI302',name:'Ethical Theories',department:'Philosophy',year:3,semester:2},
  {code:'PHI303',name:'African Philosophy (Yr 3 Sem 2)',department:'Philosophy',year:3,semester:2},
  {code:'PHI311',name:'Philosophy of Religion',department:'Philosophy',year:3,semester:2},
  {code:'PHI312',name:'Ancient Philosophy (Yr 3)',department:'Philosophy',year:3,semester:2},
  {code:'PHI313',name:'Social & Political Philosophy (Yr 3 Sem 2)',department:'Philosophy',year:3,semester:2},
  {code:'PHI318',name:'Symbolic Logic',department:'Philosophy',year:3,semester:2},
  {code:'PHI320',name:'Aquinas: Being & Essence',department:'Philosophy',year:3,semester:2},
  {code:'PHI321',name:'Augustine: On Free Will',department:'Philosophy',year:3,semester:2},
  {code:'BPHI302',name:'African Traditional Religion',department:'Philosophy',year:3,semester:2},
  {code:'BSTH315B',name:'Apostolic Vocation (Sem 2)',department:'Philosophy',year:3,semester:2},
  {code:'PHI300',name:'Philosophy in Practice',department:'Philosophy',year:3,semester:2},
  {code:'PHI401',name:'Epistemology',department:'Philosophy',year:4,semester:1},
  {code:'PHI402',name:'Topics in Logic',department:'Philosophy',year:4,semester:1},
  {code:'PHI405',name:'Comparative Philosophy',department:'Philosophy',year:4,semester:1},
  {code:'PHI406',name:'Recent Modern Philosophy',department:'Philosophy',year:4,semester:1},
  {code:'PHI408',name:'Phenomenology: Existentialism and Hermeneutics',department:'Philosophy',year:4,semester:1},
  {code:'PHI413',name:'Philosophy of Mind',department:'Philosophy',year:4,semester:1},
  {code:'BPHI407',name:'Analytic Philosophy',department:'Philosophy',year:4,semester:1},
  {code:'PHI420',name:'Heidegger: Being and Time',department:'Philosophy',year:4,semester:1},
  {code:'PHI411',name:'Philosophy of Law',department:'Philosophy',year:4,semester:2},
  {code:'PHI412',name:'Philosophy of History',department:'Philosophy',year:4,semester:2},
  {code:'PHI414',name:'Philosophy of Language',department:'Philosophy',year:4,semester:2},
  {code:'PHI417',name:'Twentieth Century Analytic Philosophy',department:'Philosophy',year:4,semester:2},
  {code:'PHI418',name:'Post Analytic Philosophy',department:'Philosophy',year:4,semester:2},
  {code:'BPHI406',name:'Topics in Metaphysics',department:'Philosophy',year:4,semester:2},
  {code:'BPHI411',name:'Metaphysical Study of Man',department:'Philosophy',year:4,semester:2},
  {code:'PHI404',name:'Marxist Philosophy',department:'Philosophy',year:4,semester:2},
  {code:'PHI407',name:'Issues in African Philosophy',department:'Philosophy',year:4,semester:2},
  {code:'PHI403',name:'Applied Ethics',department:'Philosophy',year:4,semester:2},
  {code:'CL101',name:'Canon Law',department:'Theology',year:1,semester:1},
  {code:'CCH101',name:'Church History',department:'Theology',year:1,semester:1},
  {code:'BLG101',name:'Greek',department:'Theology',year:1,semester:1},
  {code:'BHE101',name:'Hebrew',department:'Theology',year:1,semester:1},
  {code:'THEO101',name:'Fundamentals of Scripture',department:'Theology',year:1,semester:1},
  {code:'THEO102',name:'Apologetics',department:'Theology',year:1,semester:1},
  {code:'THEO103',name:'Mariology',department:'Theology',year:1,semester:1},
  {code:'THEO104',name:'Moral Theology',department:'Theology',year:1,semester:1},
  {code:'THEO107',name:'Sacramental Theology',department:'Theology',year:1,semester:1},
  {code:'THEO108',name:'Fundamental Moral Theology',department:'Theology',year:1,semester:1},
  {code:'THEO111',name:'De Deo Uno et Trino',department:'Theology',year:1,semester:1},
  {code:'THEO113',name:'Synoptic Gospels',department:'Theology',year:1,semester:1},
  {code:'THEO121',name:'Hebrew (Yr 1)',department:'Theology',year:1,semester:1},
  {code:'THEO131',name:'Environment & Times of NT',department:'Theology',year:1,semester:1},
  {code:'THEO132',name:'Pentateuch & Historical Books',department:'Theology',year:1,semester:1},
  {code:'PAT101',name:'Patrology',department:'Theology',year:1,semester:1},
  {code:'SPTH101',name:'Spiritual Theology',department:'Theology',year:1,semester:1},
  {code:'ENG101',name:'Use of English',department:'Theology',year:1,semester:1},
  {code:'CL101B',name:'Canon Law (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'CCH101B',name:'Church History (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'BLG102',name:'Greek II',department:'Theology',year:1,semester:2},
  {code:'BHE102',name:'Hebrew II',department:'Theology',year:1,semester:2},
  {code:'THEO101B',name:'Fundamentals of Scripture (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'THEO104B',name:'Moral Theology (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'THEO105',name:'Basileia tou Theou',department:'Theology',year:1,semester:2},
  {code:'THEO107B',name:'Sacramental Theology (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'THEO108B',name:'Fundamental Moral Theology (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'THEO111B',name:'De Deo Uno et Trino (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'THEO112',name:'Intro to Method of NT Exegesis',department:'Theology',year:1,semester:2},
  {code:'THEO113B',name:'Synoptic Gospels and Acts',department:'Theology',year:1,semester:2},
  {code:'THEO121B',name:'Fundamental Theology',department:'Theology',year:1,semester:2},
  {code:'THEO132B',name:'Pentateuch & Historical Books (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'PAT101B',name:'Patrology (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'SPTH101B',name:'Spiritual Theology (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'ENG101B',name:'Use of English (Sem 2)',department:'Theology',year:1,semester:2},
  {code:'CL201',name:'Canon Law (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'CCH201',name:'Church History (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'THEO201',name:'Fundamental Moral Theology (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'THEO204',name:'Prophets of the OT',department:'Theology',year:2,semester:1},
  {code:'THEO205',name:'Grace',department:'Theology',year:2,semester:1},
  {code:'THEO211',name:'OT Historical Books',department:'Theology',year:2,semester:1},
  {code:'THEO214',name:'NT Exegesis (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'THEO309',name:'De Deo Uno et Trino (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'MIS201',name:'Missiology',department:'Theology',year:2,semester:1},
  {code:'BLG201',name:'Greek II (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'BLH201',name:'Hebrew II (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'SPTH201',name:'Spiritual Theology (Yr 2)',department:'Theology',year:2,semester:1},
  {code:'PSTH204',name:'Pastoral Theology',department:'Theology',year:2,semester:1},
  {code:'PAT201',name:'Patrology II',department:'Theology',year:2,semester:1},
  {code:'CL201B',name:'Canon Law (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'CCH201B',name:'Church History (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'THEO201B',name:'Sacred Scripture',department:'Theology',year:2,semester:2},
  {code:'THEO203',name:'Christology',department:'Theology',year:2,semester:2},
  {code:'THEO204B',name:'Moral Theology (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'THEO205B',name:'Sacramental Theology (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'THEO211B',name:'Sacred Writing Corpus Johanneum',department:'Theology',year:2,semester:2},
  {code:'THEO214B',name:'Liturgy (Yr 2)',department:'Theology',year:2,semester:2},
  {code:'THEO305',name:'Ecclesiology',department:'Theology',year:2,semester:2},
  {code:'THEO309B',name:'Catholic Social Teaching',department:'Theology',year:2,semester:2},
  {code:'MIS201B',name:'Missiology (Sem 2)',department:'Theology',year:2,semester:2},
  {code:'BLG201B',name:'Biblical Greek',department:'Theology',year:2,semester:2},
  {code:'BLH201B',name:'Biblical Hebrew',department:'Theology',year:2,semester:2},
  {code:'SPTH201B',name:'Spiritual Theology (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'PSTH204B',name:'Pastoral Theology (Sem 2)',department:'Theology',year:2,semester:2},
  {code:'PAT201B',name:'Patrology (Yr 2 Sem 2)',department:'Theology',year:2,semester:2},
  {code:'METH201',name:'Research Methodology',department:'Theology',year:2,semester:2},
  {code:'CL301',name:'Canon Law (Yr 3)',department:'Theology',year:3,semester:1},
  {code:'THEO201C',name:'Fundamental Moral Theology (Yr 3)',department:'Theology',year:3,semester:1},
  {code:'THEO204C',name:'Prophets of the OT (Yr 3)',department:'Theology',year:3,semester:1},
  {code:'THEO302',name:'Christology (Yr 3)',department:'Theology',year:3,semester:1},
  {code:'THEO305B',name:'Ecclesiology (Yr 3)',department:'Theology',year:3,semester:1},
  {code:'THEO404',name:'Christology (Yr 4)',department:'Theology',year:3,semester:1},
  {code:'THEO313',name:'NT: Synoptic Gospels and Acts of the Apostles',department:'Theology',year:3,semester:1},
  {code:'THEO314',name:'NT Exegesis: John and Revelation',department:'Theology',year:3,semester:1},
  {code:'THEO317',name:'Liturgy',department:'Theology',year:3,semester:1},
  {code:'THEO408',name:'OT Exegesis: Wisdom Literature and Psalms',department:'Theology',year:3,semester:1},
  {code:'CL301B',name:'Canon Law (Yr 3 Sem 2)',department:'Theology',year:3,semester:2},
  {code:'CLP301',name:'Canon Law Praxis',department:'Theology',year:3,semester:2},
  {code:'HOM301',name:'Homiletics',department:'Theology',year:3,semester:2},
  {code:'PSY302',name:'Pastoral Psychology',department:'Theology',year:3,semester:2},
  {code:'PSTH401',name:'Pastoral Theology (Yr 3)',department:'Theology',year:3,semester:2},
  {code:'THEO302B',name:'Christology (Yr 3 Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO305C',name:'Ecclesiology (Yr 3 Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO308',name:'Virtue of Religion',department:'Theology',year:3,semester:2},
  {code:'THEO313B',name:'NT: Synoptic Gospels and Acts (Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO314B',name:'NT Exegesis: John and Revelation (Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO317B',name:'Liturgy (Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO401',name:'De Resurrectio',department:'Theology',year:3,semester:2},
  {code:'THEO402',name:'De Novissimi',department:'Theology',year:3,semester:2},
  {code:'THEO403',name:'Sacramental Theology (Yr 3)',department:'Theology',year:3,semester:2},
  {code:'THEO407',name:'Moral Theology (Yr 3)',department:'Theology',year:3,semester:2},
  {code:'THEO408B',name:'OT Exegesis: Wisdom Literature and Psalms (Sem 2)',department:'Theology',year:3,semester:2},
  {code:'THEO409',name:'OT Exegesis: Theology of the OT Prophets',department:'Theology',year:3,semester:2},
  {code:'THEO415',name:'NT Exegesis: Pauline Corpus',department:'Theology',year:3,semester:2},
  {code:'CLP401',name:'Canon Law Praxis (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'HOM401',name:'Homiletics (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'PENTE401',name:'Pentecostalism',department:'Theology',year:4,semester:1},
  {code:'PSY401',name:'Psychology',department:'Theology',year:4,semester:1},
  {code:'PSTH401B',name:'Pastoral Theology (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO132C',name:'Pentateuch & Historical Books (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO313C',name:'NT: Synoptic Gospels and Acts (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO403B',name:'Sacramental Theology (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO404B',name:'Christology (Yr 4 Sem 1)',department:'Theology',year:4,semester:1},
  {code:'THEO407B',name:'Moral Theology (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO408C',name:'OT Exegesis: Wisdom Literature and Psalms (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO409B',name:'OT Exegesis: Theology of the OT Prophets (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO415B',name:'NT Exegesis: Pauline Corpus (Yr 4)',department:'Theology',year:4,semester:1},
  {code:'THEO417',name:'Liturgy Praxis',department:'Theology',year:4,semester:1},
  {code:'CL401',name:'Canon Law (Yr 4)',department:'Theology',year:4,semester:2},
  {code:'CLP401B',name:'Canon Law Praxis (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'HOM401B',name:'Homiletics (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'PENTE401B',name:'Pentecostalism (Sem 2)',department:'Theology',year:4,semester:2},
  {code:'PSY401B',name:'Psychology (Sem 2)',department:'Theology',year:4,semester:2},
  {code:'PSTH401C',name:'Pastoral Theology (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO313D',name:'NT: Synoptic Gospels and Acts (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO314C',name:'NT Exegesis: John and Revelation (Yr 4)',department:'Theology',year:4,semester:2},
  {code:'THEO401B',name:'De Novissimi (Yr 4)',department:'Theology',year:4,semester:2},
  {code:'THEO403C',name:'Sacramental Theology (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO404C',name:'Christology (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO407C',name:'Moral Theology (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO408D',name:'OT Exegesis: Wisdom Literature and Psalms (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO409C',name:'OT Exegesis: Theology of the OT Prophets (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO415C',name:'NT Exegesis: Pauline Corpus (Yr 4 Sem 2)',department:'Theology',year:4,semester:2},
  {code:'THEO417B',name:'Liturgy Praxis (Sem 2)',department:'Theology',year:4,semester:2},
];
async function run() {
  console.log('Deleting existing courses...');
  const snap = await db.collection('courses').get();
  const b = db.batch();
  snap.docs.forEach(d => b.delete(d.ref));
  await b.commit();
  console.log('Deleted ' + snap.docs.length + ' courses.');
  let count = 0;
  for (let i = 0; i < courses.length; i += 499) {
    const batch = db.batch();
    courses.slice(i, i+499).forEach(c => {
      batch.set(db.collection('courses').doc(c.code), {...c, createdAt: admin.firestore.FieldValue.serverTimestamp()});
    });
    await batch.commit();
    count += Math.min(499, courses.length - i);
    console.log('Inserted ' + count + '/' + courses.length);
  }
  console.log('Done.');
  process.exit(0);
}
run().catch(e => { console.error(e); process.exit(1); });
